config/routes.rb
Rails.application.routes.draw do
  root to: "trips#index"

  devise_for :users, controllers: {sessions: 'users/sessions'}

  get '/users/:id', to: 'users#show', as: 'user'

  resources :trips

  get '/users/:user_id/trips', to: 'memberships#index', as: 'user_memberships'
  post '/trips/:trip_id/users', to: 'memberships#create', as: 'memberships_user'
  delete '/trips/:trip_id/users', to: 'memberships#destroy', as: 'membership_destroy'

end

app/models/trip.rb
# require 'geocoder'

class Trip < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  belongs_to :user

  validates :address, presence: true
  validates :destination_address, presence: true 
  validates :total_seats, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1}
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def all_members(trip)
    trip.users = users
  end

  def member?(user)
    user.trips.include?(self)
  end

  def admin?(user)
    self.user_id == user.id
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
	before_action :set_trip, only: [:show, :edit, :update, :destroy]
	before_action :admin_user, only: [:edit, :update, :destroy]
  before_action :find_all, except: [:destroy]

	def index
    @trip = Trip.new() #setting empty trips hash
    @key = ENV['GOOGLE_MAPS']

    if params[:search].present?
      @trips = Trip.near(params[:search], 10)
    else
      @trips = Trip.all
    end
  end

  def show
  end

	def new
    @trip = Trip.new(user_id: params[:user_id])
	end

	def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
	  if @trip.save
      Membership.create(user_id: current_user.id, trip_id: @trip.id, member_type: 1)
			flash[:success] = "Carpool added!"
      redirect_to root_path
    else
      flash[:error] = @trip.errors.full_messages.join(", ")
      redirect_to new_trip_path
    end
 end

  def edit
    @trip = Trip.find(params[:id])
    @trips = Trip.all

  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      flash[:error] = @trip.errors.full_messages.join(", ")
      render 'edit'
    end
  end

  def destroy
    @trip.destroy
    redirect_to root_path
  end

  private

	def set_trip
    @trip = Trip.find_by_id(params[:id])
  end

  def find_all
    @trips = Trip.all
  end

	def trip_params
    params.require(:trip).permit(:id, :address, :destination_address, :latitude, :longitude, :total_seats, :open_seats, :full?, :user_id)
  end

	def admin_user
		@trip = Trip.find_by_id(params[:id])
		unless @trip.admin?(current_user)
			flash[:error] = "You must be the admin to update this carpool."
			redirect_to trip_path(@trip)
		end
	end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_all_trips.html.erb
<div class="ui container">
  <div class="header">
    <h3 class="ui center aligned header"> All Rydeshares </h3>
  </div>
  <div class="ui basic segment">
    <% @trips.each do |trip| %>
      <% if !trip.admin?(current_user) && !current_user.member?(trip) %>

      <strong>Departure: </strong><%= link_to trip.address, trip_path(trip) %>
      | <strong> Destination: </strong><%= trip.destination_address %> | <strong>Driver: </strong><%= User.where(id:trip.user_id).first.first_name %>
      <%= User.where(id:trip.user_id).first.last_name %>
        <div class="ui left icon button">
          <%= link_to memberships_user_path(trip.id), method: 'post' do %>
          <i class="add user icon"></i>
          <% end %>
        </div>
      <hr>
      <% end %>

    <% end %>

  </div>
</div>

app/views/trips/_dashboard_sidebar.html.erb
<div class="ui container">
  <div class="ui basic segment">
    <div class="four wide column">
      <br>
      <div class="ui basic segment">
    	<h3 class="ui header"> Find A Rydeshare
    	</h3>
      <div class="ui form">
    	<%= form_tag trips_path, :method => :get do %>
      	<p>
        <div class="field">
          <%= text_field_tag :search, params[:search], placeholder: "Enter a city or full address" %>
        </div>

        <div class="actions">
          <%= submit_tag "Search Nearby Departures", :name => nil, class: "ui positive button"  %>
        </div>
    	<% end %>
      </div>
    	</div>
      <div>
        <%= render 'your_trips' %>
      </div>
    	<br>
      <div>
        <%= render 'all_trips' %>
      </div>
    </div>
  </div>
</div>

app/views/trips/_edit_trip.html.erb
<div class="ui basic segment">
  <div class="header">
    <h3 class="ui center aligned header">
      Update Rydeshare
    </h3>
  </div>
  <br>
  <div class="ui divider"></div>
  <div class="content">
    <div class="ui form">
      <%= form_for @trip do |f| %>
        <div class="required field">
          <%= f.label :address, 'Departure' %><br />
          <%= f.text_field :address, autofocus: true %>
        </div>
        <div class="required field">
          <%= f.label :destination_address, 'Destination' %><br />
          <%= f.text_field :destination_address, autofocus: true %>
        </div>
        <div class="required field">
          <%= f.label :total_seats, 'Total Seats' %><br />
          <%= f.text_field :total_seats, autofocus: true %>
        </div>
        <div class="actions">
          <%= f.submit "Save", class: "ui primary button" %>
        </div>
      <% end %>
    </div>
    <br>
  </div>
  <%= button_to "Delete", { action: "destroy", id: @trip.id },  method: :delete, data:
    {confirm: "Are you sure you want to delete this carpool?"}, class: "ui button" %>
</div>

app/views/trips/_gen_welcome.html.erb
<div class="ui basic segment">
  <h1 class="ui header"> Welcome to Rydeshare!</h1>
  <p> Save time, make friends and reduce your carbon footprint by carpooling. </p>
  <p>Sign up to be a Rider or Driver Today? <%= link_to 'Sign up', new_user_registration_path%></p>
  <p>Already a member? <%= link_to 'Log in', new_user_session_path%> </p>
</div>

app/views/trips/_new_trip.html.erb
<div class="ui basic segment">
  <div class="header">
    <h3 class="ui header">
      Create New Rydeshare
    </h3>
  </div>
  <br>
  <div class="ui divider"></div>
  <div class="content">
    <div class="ui form">
      <%= form_for :trip, url: '/trips', method: :post do |f| %>
        <div class="required field">
          <%= f.label :address, 'Departure' %><br />
          <%= f.text_field :address, autofocus: true %>
        </div>
        <div class="required field">
          <%= f.label :destination_address, 'Destination' %><br />
          <%= f.text_field :destination_address, autofocus: true %>
        </div>
        <div class="required field">
          <%= f.label :total_seats, 'Total Seats' %><br />
          <%= f.text_field :total_seats, autofocus: true %>
        </div>
        <div class="actions">
          <%= f.submit "Save", class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_trip.html.erb
<div class="chat twelve wide column">
  <div class="ui basic segment">
    <h3 class="ui header">
      Rydeshare Details
    </h3>
    <div class="ui divider"></div>
    <div class="content">
      <p>Driver: <%= User.where(id:@trip.user_id).first.first_name %> <%= User.where(id:@trip.user_id).first.last_name %> </p>
      <p>Address: <%= @trip.address %></p>
      <p>Coordinates: <%= @trip.latitude %>, <%= @trip.longitude %></p>
    </div>
  </div>
</div>

app/views/trips/_trip_map.html.erb
<h2 class="ui center aligned header"> Rydeshare Dashboard</h2>

<div class="ui container">
	<div class="twelve wide column">
		<div id="map">
		</div>
	</div>
</div>

<script type="text/javascript">

    var map = new GMaps({
      el: '#map',
      lat: 37.5431768,
			lng: -122.2981118,
			zoom: 10
    });

  <% @trips.each do |trip| %>
    map.addMarker({
			lat: <%= trip.latitude %>,
			lng: <%= trip.longitude %>,
			infoWindow: {
  		content: `
			<strong>Departure:</strong> <%=trip.address%> <p>
			<strong>Driver: </strong>
			<%= User.where(id:trip.user_id).first.first_name %> <%= User.where(id:trip.user_id).first.last_name %>
			<% if !trip.admin?(current_user) && current_user.member?(trip) %>
				<div class="ui left icon button">
					<%= link_to membership_destroy_path(trip.id), method: 'delete' do %>
						<i class="remove user icon"></i>
					<% end %>
				</div>
			<% elsif !trip.admin?(current_user) && !current_user.member?(trip) %>
				<div class="ui left icon button">
					<%= link_to memberships_user_path(trip.id), method: 'post' do %>
						<i class="add user icon"></i>
					<% end %>
				</div>
			<% elsif trip.admin?(current_user) %>
				<div class="ui left icon button">
					<%= link_to edit_trip_path(trip) do %>
						<%= fa_icon "pencil" %>
					<% end %>
				</div>
			<% end %>
			`

			// <strong>Departure: </strong><%= link_to trip.address, trip_path(trip) %>
			// <br>
			}
		});
  <% end %>
</script>

app/views/trips/_your_trips.html.erb
<h3 class="ui center aligned header"> Your Rydeshares <%= link_to new_trip_path do %>
  <i class="add circle icon"></i>
<% end %></h3>

<div class="ui basic segment">
  <% current_user.trips.each do |trip| %>
    <br>
    <% if trip.admin?(current_user) %>
      <strong> Departure: </strong><%= link_to trip.address, trip_path(trip) %> |
      <strong> Destination: </strong><%= trip.destination_address %>
      <!--TODO: Track full? members list -->
      <div class="ui left icon button">
        <%= link_to edit_trip_path(trip) do %>
          <%= fa_icon "pencil" %>
        <% end %>
      </div>
      <br>
    <% else %>
      <strong>Departure: </strong><%= link_to trip.address, trip_path(trip) %>
      | <strong> Destination: </strong><%= trip.destination_address %> |
      <strong>Driver: </strong><%= User.where(id:trip.user_id).first.first_name %>
      <%= User.where(id:trip.user_id).first.last_name %>
      <div class="ui left icon button">
        <%= link_to membership_destroy_path(trip.id), method: 'delete' do %>
          <i class="remove user icon"></i>
        <% end %>
      </div>

      <hr>
    <% end %>
  <% end %>
</div>

app/views/trips/edit.html.erb
<%= render partial: 'edit_trip', layout: 'layouts/trip' %>

app/views/trips/index.html.erb
<% unless user_signed_in? %>
 <%= render 'gen_welcome' %>
<% else %>
 <%= render partial: 'trip_map', layout: 'layouts/trip' %>
<% end %>

app/views/trips/new.html.erb
<%= render partial: 'new_trip', layout: 'layouts/trip' %>

app/views/trips/show.html.erb
<%= render partial: 'trip', layout: 'layouts/trip' %>	